# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8f212ca9e968cb1a2aebdfdd41f55a61820cbf457895e4760d5a716633b8e2e10c833e0800eabe08c61ca7f37bc9224f356c0d7103f0ebb7cd16f0bfc3d25ff

test:
  secret_key_base: ff7a31360e36082c9dd06034ca8fb7e67236de4c3e2b321f6f25a751c67d0703534704c03ee63440651c9ae1562bac0aa7b5d37c8fe5574acce6b11f1f0a9b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
